paypal:
  client-id: Abq82z1IDaD5jzZFMuclO1xAO2XievnfvZKpLBWX7m0SLm_3iFmDCazdJLVCvHGv1o80HJCYlOy-oqHx
  client-secret: ENrniZoWz0l-FNYyGtHx0BHMAf7NLWSBdkUw2qL0u7vH9vtPewCoLQBX0TzO_WGoAYEkqlY3QgzMvB45
  mode: sandbox

